services:
  - type: web
    name: resumerocket-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: gunicorn rewrite_engine:app
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
